server:
  port: ${API_GATEWAY_PORT:10001}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka
  instance:
    ip-address: ${EUREKA_HOST_NAME:localhost}
    hostname: ${EUREKA_HOST_NAME:localhost}

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - name: RewritePath
              args:
                regexp: "serviceId.toLowerCase() + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
            - name: AuthenticationJwtToken
              args:
                enable: true

#Grpc
grpc-service:
  auth-service:
    host-name: ${AUTH_GRPC_HOST:localhost}
    port: ${AUTH_GRPC_PORT:56565}
