server:
  port: ${ORDER_PORT:10091}
#  servlet:
#    context-path: /v1/order-service

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${DATABASE_NAME:localhost}:3306/order
    username: ${DATABASE_USER_NAME:root}
    password: ${DATABASE_USER_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka

logging:
  level:
    root: info