version: '3.4'

services:
  redis:
    image: local:redis
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    networks:
      - internal
  mysql:
    image: local:mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - internal
networks:
  internal:
    external: true