server:
  port: ${CUSTOMER_PORT:10090}
#  servlet:
#    context-path: /v1/customer-service

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://${DATABASE_NAME:localhost}:3306/customer
    username: ${DATABASE_USER_NAME:root}
    password: ${DATABASE_USER_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka

#Grpc
grpc-service:
  auth-service:
    host-name: ${AUTH_GRPC_HOST:localhost}
    port: ${AUTH_GRPC_PORT:56565}

logging:
  level:
    root: info